import { getAlertInfo, getDepthClass } from '../../modules/hazards/utils/earthquake.utils.js'
import type { EarthquakeTransformResult } from '../../modules/hazards/hazards.types.js'

type EarthquakeSeed = Omit<EarthquakeTransformResult, 'geom'> & { lng: number; lat: number }

export const earthquakes: EarthquakeSeed[] = [
  {
    usgs_id: 'ci11408890',
    magnitude: 1.3,
    magnitude_type: 'ML',
    location: '10km SSW of Idyllwild, CA',
    occurred_at: new Date('2014-01-02T01:11:36Z').toISOString(),
    depth_km: 11.0,
    depth_class: getDepthClass(11.0),
    triggered_tsunami: 'no',
    alert: getAlertInfo(null),
    lng: -116.7777,
    lat: 33.6633,
  },
  {
    usgs_id: 'ak01421ig3u',
    magnitude: 1.1,
    magnitude_type: 'ML',
    location: 'Central Alaska',
    occurred_at: new Date('2014-01-02T01:07:26Z').toISOString(),
    depth_km: 14.1,
    depth_class: getDepthClass(14.1),
    triggered_tsunami: 'no',
    alert: getAlertInfo(null),
    lng: -151.6459,
    lat: 63.102,
  },
  {
    usgs_id: 'usc000mnnn',
    magnitude: 4.0,
    magnitude_type: 'MB',
    location: '28 km WNW of Coquimbo, Chile',
    occurred_at: new Date('2014-01-02T01:02:15Z').toISOString(),
    depth_km: 40.0,
    depth_class: getDepthClass(40.0),
    triggered_tsunami: 'no',
    alert: getAlertInfo(null),
    lng: -71.621,
    lat: -29.888,
  },
  {
    usgs_id: 'us2024abc01',
    magnitude: 5.2,
    magnitude_type: 'MWW',
    location: '15 km NE of Izmir, Turkey',
    occurred_at: new Date('2024-03-15T08:22:00Z').toISOString(),
    depth_km: 10.0,
    depth_class: getDepthClass(10.0),
    triggered_tsunami: 'no',
    alert: getAlertInfo('green'),
    lng: 27.3,
    lat: 38.5,
  },
  {
    usgs_id: 'us2024abc02',
    magnitude: 6.1,
    magnitude_type: 'MWW',
    location: '30 km SW of Kathmandu, Nepal',
    occurred_at: new Date('2024-05-20T14:10:00Z').toISOString(),
    depth_km: 18.0,
    depth_class: getDepthClass(18.0),
    triggered_tsunami: 'no',
    alert: getAlertInfo('yellow'),
    lng: 85.1,
    lat: 27.7,
  },
  {
    usgs_id: 'us2024abc03',
    magnitude: 7.2,
    magnitude_type: 'MWW',
    location: 'Off coast of Honshu, Japan',
    occurred_at: new Date('2024-08-11T03:45:00Z').toISOString(),
    depth_km: 35.0,
    depth_class: getDepthClass(35.0),
    triggered_tsunami: 'yes',
    alert: getAlertInfo('orange'),
    lng: 142.5,
    lat: 38.2,
  },
  {
    usgs_id: 'us2024abc04',
    magnitude: 4.5,
    magnitude_type: 'ML',
    location: '10 km N of Tirana, Albania',
    occurred_at: new Date('2024-09-02T11:30:00Z').toISOString(),
    depth_km: 8.0,
    depth_class: getDepthClass(8.0),
    triggered_tsunami: 'no',
    alert: getAlertInfo(null),
    lng: 19.8,
    lat: 41.4,
  },
  {
    usgs_id: 'us2024abc05',
    magnitude: 5.8,
    magnitude_type: 'MWW',
    location: '45 km SE of Thessaloniki, Greece',
    occurred_at: new Date('2024-11-18T20:05:00Z').toISOString(),
    depth_km: 12.0,
    depth_class: getDepthClass(12.0),
    triggered_tsunami: 'no',
    alert: getAlertInfo('green'),
    lng: 23.4,
    lat: 40.3,
  },
]