export const eruptions = [
  {
    gvp_eruption_id: 10001,
    gvp_volcano_id: 210010,
    volcano_name: 'West Eifel Volcanic Field',
    eruption_area: 'Ulmener Maar',
    start_year: -8740,
    start_year_uncertainty: 150,
    explosivity_index: null,
    confirmed: true,
    lng: 6.85,
    lat: 50.17,
  },
  {
    gvp_eruption_id: 10003,
    gvp_volcano_id: 210020,
    volcano_name: 'Chaine des Puys',
    eruption_area: 'Western Puy de Dôme',
    start_year: -7840,
    start_year_uncertainty: 200,
    explosivity_index: null,
    confirmed: true,
    lng: 2.981,
    lat: 45.786,
  },
  {
    gvp_eruption_id: 22001,
    gvp_volcano_id: 311240,
    volcano_name: 'Etna',
    eruption_area: 'Southeast Crater',
    start_year: 2024,
    start_year_uncertainty: null,
    explosivity_index: 2,
    confirmed: true,
    lng: 15.0,
    lat: 37.75,
  },
  {
    gvp_eruption_id: 22002,
    gvp_volcano_id: 373010,
    volcano_name: 'Kilauea',
    eruption_area: 'Halemaʻumaʻu Crater',
    start_year: 2024,
    start_year_uncertainty: null,
    explosivity_index: 1,
    confirmed: true,
    lng: -155.28,
    lat: 19.41,
  },
  {
    gvp_eruption_id: 22003,
    gvp_volcano_id: 341040,
    volcano_name: 'Stromboli',
    eruption_area: 'Summit Crater',
    start_year: 2024,
    start_year_uncertainty: null,
    explosivity_index: 3,
    confirmed: true,
    lng: 15.21,
    lat: 38.79,
  },
  {
    gvp_eruption_id: 22004,
    gvp_volcano_id: 341050,
    volcano_name: 'Fagradalsfjall',
    eruption_area: 'Reykjanes Peninsula',
    start_year: 2024,
    start_year_uncertainty: null,
    explosivity_index: 1,
    confirmed: true,
    lng: -22.27,
    lat: 63.87,
  },
]
