export const tsunamis = [
  {
    noaa_id: 1,
    location: 'Syrian Coasts',
    country: 'SYRIA',
    year: -2000,
    max_wave_height_m: null,
    deaths: null,
    deaths_severity: 3,
    earthquake_magnitude: null,
    cause: 'Earthquake',
    event_validity: 1,
    intensity: 6,
    region_code: 50,
    lng: 35.8,
    lat: 35.683,
  },
  {
    noaa_id: 3,
    location: 'Thera Island (Santorini)',
    country: 'GREECE',
    year: -1610,
    max_wave_height_m: 90,
    deaths: null,
    deaths_severity: 3,
    earthquake_magnitude: null,
    cause: 'Volcano',
    event_validity: 4,
    intensity: 6,
    region_code: 50,
    lng: 25.4,
    lat: 36.4,
  },
  {
    noaa_id: 5001,
    location: 'Pacific Coast',
    country: 'JAPAN',
    year: 2011,
    max_wave_height_m: 40.5,
    deaths: 18000,
    deaths_severity: 4,
    earthquake_magnitude: 9.1,
    cause: 'Earthquake',
    event_validity: 4,
    intensity: 10,
    region_code: 30,
    lng: 142.3,
    lat: 38.1,
  },
  {
    noaa_id: 5002,
    location: 'Indian Ocean',
    country: 'INDONESIA',
    year: 2004,
    max_wave_height_m: 30.0,
    deaths: 227000,
    deaths_severity: 4,
    earthquake_magnitude: 9.1,
    cause: 'Earthquake',
    event_validity: 4,
    intensity: 9,
    region_code: 40,
    lng: 95.9,
    lat: 3.3,
  },
  {
    noaa_id: 5003,
    location: 'Ionian Sea',
    country: 'GREECE',
    year: 2018,
    max_wave_height_m: 1.5,
    deaths: 2,
    deaths_severity: 1,
    earthquake_magnitude: 6.8,
    cause: 'Earthquake',
    event_validity: 4,
    intensity: 3,
    region_code: 50,
    lng: 20.6,
    lat: 37.9,
  },
  {
    noaa_id: 5004,
    location: 'Tyrrhenian Sea',
    country: 'ITALY',
    year: 2019,
    max_wave_height_m: 1.5,
    deaths: 1,
    deaths_severity: 1,
    earthquake_magnitude: null,
    cause: 'Volcano',
    event_validity: 4,
    intensity: 2,
    region_code: 50,
    lng: 15.21,
    lat: 38.79,
  },
]
